export const CHANGE_ARTICLE_LIST='admin/home/list/CHANGE_ARTICLE_LIST'
export const CHANGE_ARTICLE_TAGS='admin/home/list/CHANGE_ARTICLE_TAGS'
export const DELETE_TAG='admin/home/list/DELETE_TAG'
export const CHOOSE_ARTICLE='admin/home/list/CHOOSE_ARTICLE'
export const CHANGE_TITLE='admin/home/list/CHANGE_TITLE'
export const CHANGE_CONTENT='admin/home/list/CHANGE_CONTENT'
export const CHANGE_TAG='admin/home/list/CHANGE_TAG'
export const DELETE_ARTICLE='admin/home/list/DELETE_ARTICLE'
